PROJECT_NETWORK_NAME="NetworkingDev"
PROJECT_ENVIRONMENT="Development"
PROJECT_COST_NAME="AWS"
PROJECT_ECS_NAME="ECSinDev"

# ECS Task Settings
ECS_IMAGE="nginx:latest"
ECS_CONTAINER_PORT=80

# ECS Service Settings
ECS_SVC_DESIRED_TASK=3